/* eslint-disable */
/**
 * Generated API.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@0.4.0.
 * To regenerate, run `npx convex codegen`.
 * @module
 */

import type { ApiFromModules } from "convex/browser";
import type * as createURL from "../createURL";
import type * as deleteURL from "../deleteURL";
import type * as getURL from "../getURL";
import type * as listURLs from "../listURLs";
import type * as storeUser from "../storeUser";

/**
 * A type describing your app's public Convex API.
 *
 * This `API` type includes information about the arguments and return
 * types of your app's query and mutation functions.
 *
 * This type should be used with type-parameterized classes like
 * `ConvexReactClient` to create app-specific types.
 */
export type API = ApiFromModules<{
  createURL: typeof createURL;
  deleteURL: typeof deleteURL;
  getURL: typeof getURL;
  listURLs: typeof listURLs;
  storeUser: typeof storeUser;
}>;
